# Chapter 2: Introduction to NumPy

The NumPy (short for *Numerical Python*) package provides an efficient interface to store and operate on dense data buffers. In some ways, NumPy arrays are like Python's built-in `list` type, but NumPy arrays provide much more efficient storage and data operators as the arrays grow larger in size.

In [3]:
import numpy as np
np.__version__

'1.22.3'

## Understanding Data Types in Python

Python is a dynamically typed language (in contrast to static typed languages like C and Java).
This means that the data types of variables are dynamically inferred:

In [ ]:
x = 4
x = "four"

The standard mutable multielement container in Python is the list.

In [5]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
type(L[0])

int

In [7]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [8]:
type(L2[0])

str

In [9]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

This dynamic flexibility comes at a cost: a Python `list` must contain the full structure/information of each object it contains.
By contrast, a NumPy array is fixed-type, and is therefore much more efficient in storing and manipulating data.

Python has a built-in `array` module that can store a uniform type:

In [10]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Here, `'i'` is a type code indicating the contents are integers.

A more useful object is the NumPy `ndarray`, which adds efficient *operations* on the data (explored later in this section).

In [11]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

If types in the given list do not match, `np.array()` will upcast if possible (here, integers are upcast to floating point):

In [12]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

The `dtype` keyword can be used to explicitly set the data type:

In [13]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

Finally, unlike Python lits, NumPy arrays can be explicitly multidimensional:

In [15]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Especially for larger arrays, it is more efficient to create arrays from scratch using NumPy's built-in functions:

In [16]:
# Create a length 10 integer array filled with zeroes
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [20]:
# Create an array filled with a linear sequence 0 to 20, stepping by 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
# Create a 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((3, 3))

array([[0.11951912, 0.41018534, 0.27538936],
       [0.58023666, 0.72172228, 0.51023194],
       [0.84901395, 0.57661238, 0.21919099]])

In [24]:
# Create a 3x3 array of noramlly distributed random values with mean 0 and SD 1
np.random.normal(0, 1, (3, 3))

array([[ 1.95286972, -0.2192877 ,  0.85160344],
       [-1.1392111 , -0.68290616, -2.05889299],
       [ 0.20443203,  0.76397592, -0.37174   ]])

In [25]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[1, 3, 5],
       [6, 2, 8],
       [4, 6, 6]])

In [26]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

When constructing an array, you can specify data type with a string:

In [28]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

Or using the associated NumPy object:

In [29]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)