# Chapter 3: Data Manipulation with Pandas

Pandas is a package built on top of NumPy that provides efficient implementation of a `DataFrame`: milti-dimensional arrays with row and column labels, and often with heterogenous types and/or missing data.

In [15]:
import numpy as np
import pandas as pd
pd.__version__

'1.4.1'

## Introducting Pandas Objects

### The Pandas Series Object

A Pandas `Series` is a one-dimensional array of indexed data.

In [16]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [17]:
# Access the `values` and `index` attributes
data.values, data.index

(array([0.25, 0.5 , 0.75, 1.  ]), RangeIndex(start=0, stop=4, step=1))

In [18]:
# Access values by position
data[1], data[1:3]

(0.5,
 1    0.50
 2    0.75
 dtype: float64)

The key difference between a Pandas `Series` and a 1-d NumPy array is that the former has an *explicitly defined* index, as opposed to implicitly defined.

In [19]:
# Use strings as an index
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a', 'b', 'c', 'd'])
data, data['b']

(a    0.25
 b    0.50
 c    0.75
 d    1.00
 dtype: float64,
 0.5)

In [20]:
# Noncontiguous or nonsequential indices
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = [2, 5, 3, 7])
data, data[5]

(2    0.25
 5    0.50
 3    0.75
 7    1.00
 dtype: float64,
 0.5)

In this way, the `Series` is a bit like a Python dictionary, that maps keys to values. The difference is that the keys and values must be typed.

In [22]:
# Construct a Series from a dictionary
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population, population['California']

(California    38332521
 Texas         26448193
 New York      19651127
 Florida       19552860
 Illinois      12882135
 dtype: int64,
 38332521)

In [26]:
# Unlike a dictionary, we can use array-style operations
# Note that, in the text, the keys were automatically sorted alphabetically
population['California':'New York']

California    38332521
Texas         26448193
New York      19651127
dtype: int64

In [27]:
# A single value will fill the given indices
pd.Series(5, index = [100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [28]:
# Unlike the text, this newer version of Pandas does not automatically sort dictionary keys
pd.Series({2: 'a', 1: 'b', 3: 'c'})

2    a
1    b
3    c
dtype: object

In [29]:
# Explicitly setting the index can return specific values
pd.Series({2: 'a', 1: 'b', 3: 'c'}, index = [3, 2])

3    c
2    a
dtype: object

### The Pandas DataFrame Object

A Pandas `DataFrame` can be thought of as a two-dimensional array with flexible row indicies and column names, or as a sequence of aligned `Series` objects.

In [31]:
# First, create a Series from a dictionary
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [33]:
# Now create a single two-dimensional DataFrame from two Series
states = pd.DataFrame({'population': population, 'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [34]:
# Column and index attributes
states.index, states.columns

(Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object'),
 Index(['population', 'area'], dtype='object'))

In [35]:
# We can access a Series object like we would a dictionary
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [36]:
# A single column DataFrame from a Series
pd.DataFrame(population, columns = ['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [38]:
# From a list of dictionaries
data = [{'a': i, 'b': 2 * i} for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [39]:
# If some keys are missing, Pandas will fill them with NaN
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [40]:
# From a two-dimensional NumPy array
pd.DataFrame(np.random.rand(3, 2), columns = ['foo', 'bar'], index = ['a', 'b', 'c'])

foo       bar
a  0.343428  0.916239
b  0.099089  0.238774
c  0.427762  0.271313

In [45]:
# From astructured NumPy array
A = np.zeros(3, dtype = [('A', 'i8'), ('B', 'f8')])
A, pd.DataFrame(A)


(array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')]),
    A    B
 0  0  0.0
 1  0  0.0
 2  0  0.0)

### The Pandas Index Object

The Pandas `Index` object can be thought of as an *ummutable array* or as an *ordered set*.

In [46]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [47]:
# Access elements like an array
ind[1], ind[::2]

(3, Int64Index([2, 5, 11], dtype='int64'))

In [48]:
# Attributes
ind.size, ind.shape, ind.ndim, ind.dtype

(5, (5,), 1, dtype('int64'))

In [49]:
# Index objects are immutable, so they cannot be modified by normal means
ind[1] = 0

TypeError: Index does not support mutable operations

The Pandas `Index` objects follows many of the conventions used by the built-in `set` data structure.

In [50]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])
# intersection
indA & indB

C:\Users\tdunn\AppData\Local\Temp\ipykernel_12224\2322778381.py:4: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead.
  indA & indB


Int64Index([3, 5, 7], dtype='int64')

The deprecation warning tells us to use `index.intersection()` instead (likewise for unions and symmetric differences):

In [51]:
indA.intersection(indB)

Int64Index([3, 5, 7], dtype='int64')

In [52]:
indA.union(indB)

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [54]:
indA.symmetric_difference(indB)

Int64Index([1, 2, 9, 11], dtype='int64')

## Data Indexing and Selection

### Data Selection in Series

In [55]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a', 'b', 'c', 'd'])
# Dictionary-like expressions to examine keys/indices and values
'a' in data, data.keys(), list(data.items())

(True,
 Index(['a', 'b', 'c', 'd'], dtype='object'),
 [('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)])

In [56]:
# Extend a Series
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [57]:
# Slicing
# Notice that explicit 'a':'c' slicing includes the last element, but implicit 0:2 slicing does not
data['a':'c'], data[0:2]

(a    0.25
 b    0.50
 c    0.75
 dtype: float64,
 a    0.25
 b    0.50
 dtype: float64)

In [58]:
# Masking and fancy indexing
data[(data > 0.3) & (data < 0.8)], data[['a', 'e']]

(b    0.50
 c    0.75
 dtype: float64,
 a    0.25
 e    1.25
 dtype: float64)

In [59]:
data = pd.Series(['a', 'b', 'c'], index = [1, 3, 5])
# Confusion: explicit index vs implicit index when slicing
data[1], data[1:3]

('a',
 3    b
 5    c
 dtype: object)

In [61]:
# Use Pandas indexers to distinguish slicing interfaces
# `loc` always references explicit index
data.loc[1], data.loc[1:3]

('a',
 1    a
 3    b
 dtype: object)

In [62]:
# `iloc` always references implicit index
data.iloc[1], data.iloc[1:3]

('b',
 3    b
 5    c
 dtype: object)

### Data Selection in DataFrame

In [64]:
data = pd.DataFrame({'area': area, 'pop': population})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [65]:
# Access the individual Series objects that make up the columns
data['area'] is data.area

True

In [67]:
# But careful with column names that conflict with methods like `pop()`
data.pop is data['pop']

False

In [69]:
# Add a new column
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [70]:
# The `values` attribute returns the underlying 2d array
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [71]:
# With this array picture in mind, we can do array-like operations like transpose
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [75]:
# But there are important differences from arrays
# Passing a single index to an array accesses a row, passing a single index to a DataFrame access a column
data.values[0], data['area']

(array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01]),
 California    423967
 Texas         695662
 New York      141297
 Florida       170312
 Illinois      149995
 Name: area, dtype: int64)

In [77]:
# For array-style indexing, use `iloc`
data.iloc[:3, :2], data.loc[:'Texas', :'pop']

(              area       pop
 California  423967  38332521
 Texas       695662  26448193
 New York    141297  19651127,
               area       pop
 California  423967  38332521
 Texas       695662  26448193
 New York    141297  19651127
 Florida     170312  19552860
 Illinois    149995  12882135)

In [78]:
# The `ix` indexer allows a hybrid of approaches
data.ix[:3, :'pop']

AttributeError: 'DataFrame' object has no attribute 'ix'

It turns out that this form of indexing was deprectated and removed from Pandas.

In [80]:
# Masking and fancy indexing
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [ ]:
# Setting or modifying values like an array
data.iloc[0, 2] = 90

## Operating on Data in Pandas

### Ufuncs: Index Preservation

In [82]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
df = pd.DataFrame(rng.randint(0, 10, (3, 4)), columns = ['A', 'B', 'C', 'D'])
ser, df

(0    6
 1    3
 2    7
 3    4
 dtype: int32,
    A  B  C  D
 0  6  9  2  6
 1  7  4  3  7
 2  7  2  5  4)

In [84]:
# Appllying a NumPy ufunc will returns the same object with the indicies preserved
np.exp(ser), np.sin(df * np.pi / 4)

(0     403.428793
 1      20.085537
 2    1096.633158
 3      54.598150
 dtype: float64,
           A             B         C             D
 0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
 1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
 2 -0.707107  1.000000e+00 -0.707107  1.224647e-16)

### Ufuncs: Index Alignment

In [87]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name = 'area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name = 'population')
area / population

Alaska             NaN
California    0.011060
New York           NaN
Texas         0.026303
dtype: float64

The resulting array contains the *union* of indices of the two inputs, and any item with a missing entry is marked with `NaN`.

In [88]:
A = pd.Series([2, 4, 6], index = [0, 1, 2])
B = pd.Series([1, 3, 5], index = [1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [89]:
# Use the appropriate methods to provide `fill_value`
A.add(B, fill_value = 0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [94]:
# Alignment by column and index
A = pd.DataFrame(rng.randint(0, 20, (2, 2)), columns = list('AB'))
B = pd.DataFrame(rng.randint(0, 10, (3, 3)), columns = list('BAC'))
A, B, A + B

(    A   B
 0  15  12
 1  17  14,
    B  A  C
 0  4  7  9
 1  8  8  0
 2  8  6  8,
       A     B   C
 0  22.0  16.0 NaN
 1  25.0  22.0 NaN
 2   NaN   NaN NaN)

In [97]:
# Stack rows and get the mean of all values
A_mean = A.stack().mean()
# Fill missing values with mean of A
A.add(B, fill_value = A_mean)

A     B     C
0  22.0  16.0  23.5
1  25.0  22.0  14.5
2  20.5  22.5  22.5

### Ufuncs: Operations Between DataFrame and Series

In [98]:
# Subtracting a 2-d array from one of its rows is applied row-wise
# Array broadcasting: (3, 4) - (1, 4) -> (3, 4)
A = rng.randint(10, size = (3, 4))
A, A  - A[0]

(array([[7, 0, 7, 7],
        [2, 0, 7, 2],
        [2, 0, 4, 9]]),
 array([[ 0,  0,  0,  0],
        [-5,  0,  0, -5],
        [-5,  0, -3,  2]]))

In [122]:
# Pandas also operates row-wise by default
df = pd.DataFrame(A, columns = list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -5  0  0 -5
2 -5  0 -3  2

In [123]:
# Column-wise operations can be done with the object methods and `axis` argument
df.subtract(df['R'], axis = 0)

Q  R  S  T
0  7  0  7  7
1  2  0  7  2
2  2  0  4  9

In [124]:
# Operations betwen DataFrames and Series will align indices
df_half_rows = df.iloc[0, ::2]
df_half_rows, df - df_half_rows

(Q    7
 S    7
 Name: 0, dtype: int32,
      Q   R    S   T
 0  0.0 NaN  0.0 NaN
 1 -5.0 NaN  0.0 NaN
 2 -5.0 NaN -3.0 NaN)

In [118]:
df.keys()

Index(['Q', 'R', 'S', 'T'], dtype='object')

KeyError: 'T'

In [116]:
?pd.DataFrame.loc

Type:        property
String form: <property object at 0x000001D3F9E52C70>
Docstring:  
Access a group of rows and columns by label(s) or a boolean array.

``.loc[]`` is primarily label based, but may also be used with a
boolean array.

Allowed inputs are:

- A single label, e.g. ``5`` or ``'a'``, (note that ``5`` is
  interpreted as a *label* of the index, and **never** as an
  integer position along the index).
- A list or array of labels, e.g. ``['a', 'b', 'c']``.
- A slice object with labels, e.g. ``'a':'f'``.

  .. warning:: Note that contrary to usual python slices, **both** the
      start and the stop are included

- A boolean array of the same length as the axis being sliced,
  e.g. ``[True, False, True]``.
- An alignable boolean Series. The index of the key will be aligned before
  masking.
- An alignable Index. The Index of the returned selection will be the input.
- A ``callable`` function with one argument (the calling Series or
  DataFrame) and that returns valid output f

## Handling Missing Data

### Trade-Offs in Missing Data Conventions

### Missing Data in Pandas

### Operating on Null Values

## Hierarchical Indexing

### A Multiply Indexed Series

### Methods of MultiIndex Creation

### Indexing and Slicing a MultiIndex

### Rearranging Multi-Indices

### Data Aggregation on Mutli-Indices